### ISSUE TITLE
感谢，极简的架子！

### ISSUE THREAD

**Issue by mydevc** [magdsnail/vue-viewUI-admin#1]
后台管理这样的架子非常好，如果把动态路由加上就更好了。我试着加一下。新手。

**Comment by magdsnail** [comment]
> 后台管理这样的架子非常好，如果把动态路由加上就更好了。我试着加一下。新手。
谢谢好的，我也学习一下

**Comment by magdsnail** [comment]
> 后台管理这样的架子非常好，如果把动态路由加上就更好了。我试着加一下。新手。

谢谢，好的，我也学习一下

**Comment by magdsnail** [comment]
@mydevc 谢谢，好的，我也学习一下
